#include <stdio.h>
/*
	https://projecteuler.net/problem=2
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main(int argc, char const *argv[])
{
	static int sum;
	int fib = 2;
	int fibprev1 = 1;
	int tempfib;
	for (;fib < 4000000;) {
		if (fib % 2 == 0) {
			sum += fib;
		}
		tempfib = fib;
		fib = fib + fibprev1;
		fibprev1 = tempfib;
	}
	printf("%d", sum);
	return 0;
}